package com.olvind.muigen

object FunctionTypes {
  def apply(compName: String, name: String): String =
    (compName, name) match {
      case ("MuiAppBar", "onLeftIconButtonTouchTap") => "ReactTouchEvent => Callback"
      case ("MuiAppBar", "onRightIconButtonTouchTap") => "ReactTouchEvent => Callback"
      case ("MuiAppBar", "onTitleTouchTap") => "ReactTouchEvent => Callback"
      case ("MuiDatePicker", "onChange") => "(js.UndefOr[Nothing], js.Date) => Callback"
      case ("MuiDatePicker", "onDismiss") => "Callback"
      case ("MuiDatePicker", "onFocus") => "ReactEvent => Callback"
      case ("MuiDatePicker", "onShow") => "Callback"
      case ("MuiDialog", "onDismiss") => "Callback"
      case ("MuiDialog", "onShow") => "Callback"
      case ("MuiDialog", "onRequestClose") => "Boolean => Callback"
      case ("MuiDropDownMenu", "onChange") => "(ReactEvent, Int, js.Any) => Callback"
      case ("MuiIconButton", "onBlur") => "ReactEvent => Callback"
      case ("MuiIconButton", "onFocus") => "ReactEvent => Callback"
      case ("MuiIconMenu", "onItemTouchTap") => "(ReactTouchEvent, ReactElement) => Callback"
      case ("MuiIconMenu", "onChange") => "(ReactEvent, js.UndefOr[String]) => Callback"
      case ("MuiLeftNav", "onChange") => "(ReactEvent, Int, js.Any) => Callback"
      case ("MuiLeftNav", "onNavOpen") => "Callback"
      case ("MuiLeftNav", "onNavClose") => "Callback"
      case ("MuiListItem", "onKeyboardFocus") => "(ReactKeyboardEvent, Boolean) => Callback"
      case ("MuiListItem", "onMouseLeave") => "ReactMouseEvent => Callback"
      case ("MuiListItem", "onMouseEnter") => "ReactMouseEvent => Callback"
      case ("MuiListItem", "onNestedListToggle") => "js.Any => Callback"
      case ("MuiListItem", "onTouchStart") => "ReactTouchEvent => Callback"
      case ("MuiListItem", "onTouchTap") => "ReactTouchEvent => Callback"
      case ("MuiMenu", "onEscKeyDown") => "ReactKeyboardEvent => Callback"
      case ("MuiMenu", "onItemTouchTap") => "(ReactTouchEvent, ReactElement) => Callback"
      case ("MuiMenu", "onChange") => "(ReactEvent, String | js.Array[String]) => Callback"
      case ("MuiPopover", "onRequestClose") => "Callback"
      case ("MuiSelectField", "onBlur") => "ReactEvent => Callback"
      case ("MuiSelectField", "onChange") => "(ReactEvent, Int, js.Any) => Callback"
      case ("MuiSelectField", "onFocus") => "ReactEvent => Callback"
      case ("MuiSlider", "onBlur") => "ReactEvent => Callback"
      case ("MuiSlider", "onChange") => "(ReactEvent, Double) => Callback"
      case ("MuiSlider", "onDragStart") => "ReactDragEvent => Callback"
      case ("MuiSlider", "onDragStop") => "ReactDragEvent => Callback"
      case ("MuiSlider", "onFocus") => "ReactEvent => Callback"
      case ("MuiSnackbar", "onActionTouchTap") => "ReactTouchEvent => Callback"
      case ("MuiSnackbar", "onDismiss") => "Callback"
      case ("MuiSnackbar", "onShow") => "Callback"
      case ("MuiCheckbox", "onCheck") => "(ReactEvent, Boolean) => Callback"
      case ("MuiRadioButtonGroup", "onChange") => "(ReactEvent, String) => Callback"
      case ("MuiToggle", "onToggle") => "(ReactEvent, Boolean) => Callback"
      case ("MuiTable", "onRowSelection") => "String | js.Array[Int] => Callback"
      case ("MuiTable", "onCellClick") => "(Int, Int) => Callback"
      case ("MuiTable", "onRowHover") => "Int => Callback"
      case ("MuiTable", "onRowHoverExit") => "Int => Callback"
      case ("MuiTable", "onCellHover") => "(Int, Int) => Callback"
      case ("MuiTable", "onCellHoverExit") => "(Int, Int) => Callback"
      case ("MuiTableHeader", "onSelectAll") => "Boolean => Callback"
      case ("MuiTab", "onActive") => "ReactElement => Callback"
      case ("MuiTabs", "onChange") => "(String, ReactEvent, ReactElement) => Callback"
      case ("MuiTextField", "onBlur") => "ReactEvent => Callback"
      case ("MuiTextField", "onChange") => "ReactEvent => Callback"
      case ("MuiTextField", "onEnterKeyDown") => "ReactEvent => Callback"
      case ("MuiTextField", "onFocus") => "ReactEvent => Callback"
      case ("MuiTimePicker", "onChange") => "(js.UndefOr[Nothing], js.Date) => Callback"
      case ("MuiTimePicker", "onDismiss") => "Callback"
      case ("MuiTimePicker", "onFocus") => "ReactEvent => Callback"
      case ("MuiTimePicker", "onShow") => "Callback"
    }
}
